export const paths = {
  home: '/',
  admin: {
    dashboard: '/admin/dashboard',
    sliders: '/admin/sliders',
    brands: '/admin/brands',
    categories: '/admin/categories',
    products: '/admin/products',
    users: '/admin/users',
    roles: '/admin/roles',
    permissions: '/admin/permissions',
    orders: '/admin/orders',
    coupons: '/admin/coupons',
    contacts: '/admin/contacts',
    reviews: '/admin/reviews',
    risk: '/admin/risk',
  },
  owner: {
    dashboard: '/owner/dashboard',
    orders: '/owner/orders',
    products: '/owner/products',
  },
  customer: {
    home: '/',
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    products: '/products',
    productDetail: '/products/:slug',
    productDetailOld: '/customer/products/:slug',
    cart: '/cart',
    cartOld: '/customer/cart',
    checkout: '/checkout',
    checkoutOld: '/customer/checkout',
    account: '/account',
    wishlist: '/wishlist',
    about: '/about',
    sustainability: '/sustainability',
    help: '/help',
    contact: '/contact',
    blog: '/blog',
    blogArticle: '/blog/:id',
    paymentResult: '/payment-result',
    paymentStatus: '/payment-status',
  },
} as const;

export type Paths = typeof paths;

